spring:
  datasource:
    url: jdbc:h2:mem:ewmdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 9090

stats-service:
  url: http://stats-service:9091
