version: '3.8'

services:
  stats-server:
    image: eclipse-temurin:21-jre-alpine
    container_name: stats-server
    command: ["sleep", "3600"]
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats

  ewm-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: ewm-service
    command: ["sleep", "3600"]
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm
