services:
  stats-service:
    build:
      context: ./stats-service/stat-svc-service
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    build:
      context: ./ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
