services:
  stats-service:
    container_name: stats-service
    build:
      context: ./stats-service/stat-svc-service
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    container_name: ewm-service
    build:
      context: ./ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
