version: '3.8'

services:
  stats-server:
    build:
      context: ./stats-service/stat-svc-service
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]
      interval: 5s
      timeout: 3s
      retries: 10

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats

  ewm-service:
    image: alpine:latest
    container_name: ewm-service
    command: ["sleep", "infinity"]
    ports:
      - "8080:8080"

  stats-client:
    build:
      context: ./stats-service/stat-svc-client
      dockerfile: Dockerfile
    container_name: stats-client
    ports:
      - "8081:8081"
    environment:
      STATS_SERVICE_URL: http://stats-server:9090
    depends_on:
      - stats-server

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm
