version: '3.8'

services:
  stats-server:
    build:
      context: ./stats-service
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: ewm-service
    command: ["sleep", "infinity"]
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
